@startuml 'diagram class MyMoneyRelax'

hide empty members



class JSplitPanel #LightGreen

class ImagePanel 


class DbChooserPanel

WelcomePanel -|> JSplitPanel

WelcomePanel "left" *-- ImagePanel
WelcomePanel "right" *-- DbChooserPanel






@enduml