@startuml 'diagram class MyMoneyRelax'

object welcome_panel
welcome_panel : name = "welcome_panel"

object image_panel 
image_panel : name = "image_panel"

object db_chooser_panel 
db_chooser_panel : name = "db_chooser_panel"

object cur_db
cur_db : uri = "http://hostname:port/database"

object db_list 
db_list : name = "db_list"

object data 

object valid_btn
valid_btn : name = "valid_btn"

object cur_cred
cur_cred : login = "couchdb"
cur_cred : pwd = "couchdb"

welcome_panel "leftComponent" *-- image_panel
welcome_panel "rightComponent" *-- db_chooser_panel
cur_db -* db_chooser_panel
db_chooser_panel -* cur_cred
db_chooser_panel *-- data
db_chooser_panel --> db_list
data <- db_list
db_chooser_panel --> valid_btn

@enduml