@startuml "Money App - class diagram"


class Money {
    - {static} String appName
    - {static} String appVersion
    - {static} String appDate
    + Money()
    - {static} void readProperties()
    - {static} void createAndShowGUI()
    + {static} void main()
}

JSplitPane <|-- Money
Money -* JFrame
JFrame *- JMenuBar
JMenuBar *- "5" JMenu
JMenu *- "*" JMenuItem
Money *-- "2" JLabel


@enduml