@startuml "money java activités"

start
:welcome;
:enable menu items;
note left
    Comptes
    Categories
    Recherche
end note
repeat
    split
        split
            -> "Comptes" item;
            :accounts;
        split again
            -> "Categories" item;
            :categories;
        split again
            -> "Recherche" item;
            :search;
        end split
        :operation list;
    split again
        -> "Aide" item;
        :help;
    split again
        -> "Quitter" item;
    end split
repeat while ( close window ? )
-> Yes;
end
@enduml