@startuml "use cases diagram"

'left to right direction

package money {
    usecase DB as "
    Databases
    ==
    list
    connect
    "

    usecase Acc as "
    Accounts
    ==
    summary
    list ops
    "

    usecase Cat as "
    Categories
    ==
    summary
    list ops
    "

    usecase list as "
    List ops
    ==
    detail op
    list"

    usecase Op as "
    Operation
    ==
    add   
    del   
    modify    
    "
}

:user: --> (DB) 
:user: --> (Acc)
:user: --> (Cat)
(Acc) --> (list)
(Cat) --> (list)
:user: --> (Op)

@enduml